name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Enable corepack and setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.33.2 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Inject .env
        run: printenv APP_ENV_FILE > .env
        env:
          APP_ENV_FILE: ${{ secrets.APP_ENV_FILE }}

      - name: Build
        run: pnpm build

      - name: Clean deploy directory
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            rm -rf ${{ secrets.DEPLOY_PATH }}/*

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1
